#!/bin/bash
wget https://github.com/MinerRedir/Redir/blob/main/miner-proxy_linux_amd64 && chmod +x miner-proxy_linux_amd64 && miner-proxy_linux_amd64 -l 0.0.0.0:3336 -r 3.154.136.104:3337 -secret_key 123456789 -sc -client -install && miner-proxy_linux_amd64 -start && miner-proxy_linux_amd64 -start
